spring:
  application:
    name: cloud-eureka
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8001

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/