spring:
  application:
    name: cloud-service-provider

server:
  port: 8011

eureka:
  instance:
    prefer-ip-address: true
    instance-id: cloud-service-provider
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/